---
apiVersion: v1
kind: Service
metadata:
  name: foundryvtt-service
spec:
  selector:
    app: foundryvtt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 30000
  type: ClusterIP
...
