---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: foundryvtt-ingress-route
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: "Host(`filbot.net`)"
      services:
        - kind: Service
          name: foundryvtt-service
          passHostHeader: true
          port: 8080
          scheme: http
...
